
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: places-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: places_api
      DB_USERNAME: laravel
      DB_PASSWORD: laravel_api

  postgres:
    image: postgres:15
    container_name: places-api-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: places_api
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel_api
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - 5432:5432

  nginx:
    image: nginx:alpine
    container_name: places-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
